import CottLean.Physics.Triality
import Mathlib.Tactic.IntervalCases

/-!
# The Eisenstein units as the Standard Model's ℤ₆

The Standard Model's gauge group is (SU(3) × SU(2) × U(1)) / ℤ₆. That ℤ₆ ties hypercharge to
color triality `t` and isospin doublet-ness `d`. This file shows that the units of the Eisenstein
product are a cyclic ℤ₆ generated by `1 = T(1,1)`, and records the SM assignment as data.

**What is input, not result.** Reading the ζ₃-part of a unit as color's center and the sign as
SU(2)'s center is taken from the Standard Model. The table at the bottom checks that this
encoding is consistent with the known fields. It predicts nothing.
-/

namespace T


/-! ## Which products respect the mod-(1 − ω) reduction -/

/-- `tri` is multiplicative for `qtimes a b` exactly when `a + b ≡ 1 (mod 3)`. -/
theorem tri_qtimes_iff (a b : ℤ) :
    (∀ x y : T, tri (qtimes a b x y) = tri x * tri y) ↔ ((a : ZMod 3) + b = 1) := by
  constructor
  · intro h
    have := h «ω» «ω»
    simp only [tri, qtimes, «ω»] at this; push_cast at this
    linear_combination this
  · intro h x y
    simp only [tri, qtimes]; push_cast
    linear_combination ((x.p : ZMod 3) * y.p) * h

/-! ## The six units -/

/-- The Eisenstein norm, `q² + b·pq − a·p²` with `a = b = −1`. -/
def eisNorm (x : T) : ℤ := x.q ^ 2 - x.p * x.q + x.p ^ 2

def units6 : List T := [⟨0,1⟩, ⟨1,1⟩, ⟨1,0⟩, ⟨0,-1⟩, ⟨-1,-1⟩, ⟨-1,0⟩]

/-- Exactly six pairs have Eisenstein norm 1. -/
theorem eisNorm_eq_one_iff (x : T) : eisNorm x = 1 ↔ x ∈ units6 := by
  constructor
  · intro h
    obtain ⟨p, q⟩ := x
    simp only [eisNorm] at h
    have hp1 : p ≤ 1 := by nlinarith [sq_nonneg (2*q - p)]
    have hp2 : -1 ≤ p := by nlinarith [sq_nonneg (2*q - p)]
    have hq1 : q ≤ 1 := by nlinarith [sq_nonneg (2*p - q)]
    have hq2 : -1 ≤ q := by nlinarith [sq_nonneg (2*p - q)]
    interval_cases p <;> interval_cases q <;> simp_all [units6]
  · intro h
    simp only [units6, List.mem_cons, List.not_mem_nil, or_false] at h
    rcases h with h|h|h|h|h|h <;> subst h <;> decide

/-- Every one of them has an inverse among the six. -/
theorem units6_inverse : ∀ u ∈ units6, ∃ v ∈ units6, eis u v = «0» := by decide

/-- Powers under the Eisenstein product. -/
def eisPow (x : T) : ℕ → T
  | 0 => «0»
  | n + 1 => eis (eisPow x n) x

/-- `1 = T(1,1)` generates all six, in this order, and has order exactly 6. -/
theorem one_generates :
    (List.range 6).map (eisPow «1») = units6 ∧ eisPow «1» 6 = «0» := by decide

/-- Its square is `ω` (order 3, color's center) and its cube is `_0 = −1` (order 2, SU(2)'s). -/
theorem one_sq_cube : eisPow «1» 2 = «ω» ∧ eisPow «1» 3 = «_0» := by decide

/-- The mod-(1 − ω) reduction cannot see the ℤ₃ part: it sends `ω` to 1, and reads only the sign. -/
theorem tri_blind_to_mu3 : tri «ω» = 1 ∧ tri (eisPow «1» 3) = -1 := by decide

/-! ## The Standard Model table — input, checked for consistency -/

/-- A field with `6Y`, doublet-ness `d` (1 = SU(2) doublet), and color triality `t`. -/
structure Field where
  name : String
  y6 : ℤ
  d : ℤ
  t : ℤ

def sm : List Field :=
  [⟨"Q_L", 1, 1, 1⟩, ⟨"u_R", 4, 0, 1⟩, ⟨"d_R", -2, 0, 1⟩,
   ⟨"L_L", -3, 1, 0⟩, ⟨"e_R", -6, 0, 0⟩, ⟨"H", 3, 1, 0⟩]

/-- The field's unit is `1^(6Y)`. By CRT, its exponent mod 2 is `d` and mod 3 is `t`
for every field in the table: the ℤ₆ quotient, as a statement about T's unit group. -/
theorem sm_consistent : ∀ f ∈ sm, f.y6 % 2 = f.d ∧ f.y6 % 3 = f.t := by decide

end T
