import CottLean.T.CommonMeadow

/-!
# Fracpairs, read in T

Bergstra and Ponse's fracpairs (*Fracpairs and fractions over a reduced commutative ring*, 2016) are
pairs `p/q` of integers with `q = 0` allowed. Their `+`, `·` and `−` are T's, formula for formula:

```
p/q + r/s = (ps + rq)/(qs)      p/q · r/s = (pr)/(qs)      −(p/q) = (−p)/q
```

They differ from T in two places, and this file states both in T's terms.

**The inverse** is `(p/q)⁻¹ = (q·q)/(p·q)`. That is T's reciprocal with both coordinates multiplied by
`q` (`finv_eq_scale`), so it agrees with T's reciprocal where `q = 1` and sends every quarter turn to `0ω`
(`finv_quarterTurn`). With it, the map to the common meadow `ℚₐ` respects every operation
(`toQa_finv`). That is exactly the repair `CommonMeadow.no_surjective_hom_Qa` says T's own reciprocal
cannot have.

**The equivalence** is generated by `x·z / y·(z·z) = x / y·z`. In T's terms, a pair may be multiplied by
a factor its denominator already contains (`FracStep`). The generated relation (`FracRel`) is already a
congruence for `+`, `·`, `−` and the inverse (`fracRel_plus`, `fracRel_times`, `fracRel_neg`,
`fracRel_finv`), so its classes are the fracpairs. It:

* identifies every quarter turn with `0ω` (`z = 0`), so `1/0 = 0/0` (`fracRel_omega_zeroOmega`);
* identifies a top negative with a bottom negative (`z = −1`), so `−1 = _1` (`fracRel_negOne`), and the
  orientation T keeps is gone;
* identifies `T(1,2)` with `T(2,4)` (`fracRel_half`), but **keeps the primes of the denominator**
  (`denomPrimes_of_fracRel`). So `2/2 ≠ 1/1` and `0·(1/2) = T(0,2) ≠ 0` in fracpairs (`not_fracRel_*`).
  T keeps the whole denominator here, `ℚₐ` keeps none of it, and fracpairs keep its prime support.

Bergstra and Ponse show that fracpairs over ℤ are the initial common meadow, and that `ℚₐ` is a
homomorphic image of them. `toQa_of_fracRel` is the second half of that, stated for T.
-/

namespace T

/-! ## The inverse -/

/-- The fracpair inverse, `(p/q)⁻¹ = (q·q)/(p·q)`. -/
def finv (x : T) : T := ⟨x.q * x.q, x.p * x.q⟩

/-- It is T's reciprocal with both coordinates multiplied by the denominator. -/
theorem finv_eq_scale (x : T) : finv x = scale x.q (reciprocal x) := by
  ext <;> simp [finv, scale, reciprocal]; ring

/-- So it sends every quarter turn, and `0ω`, to `0ω`. -/
theorem finv_quarterTurn {x : T} (h : x.q = 0) : finv x = «0ω» := by
  ext <;> simp [finv, h, «0ω»]

/-- With the fracpair inverse, the map to `ℚₐ` respects the inverse everywhere. -/
theorem toQa_finv (x : T) : toQa (finv x) = Qa.inv (toQa x) := by
  by_cases hq : x.q = 0 <;> by_cases hp : x.p = 0
  · simp [toQa, Qa.inv, finv, hq]
  · simp [toQa, Qa.inv, finv, hq]
  · simp [toQa, Qa.inv, finv, hq, hp]
  · have hp' : (x.p : ℚ) ≠ 0 := by exact_mod_cast hp
    have hq' : (x.q : ℚ) ≠ 0 := by exact_mod_cast hq
    simp [toQa, Qa.inv, finv, hq, hp, hp', hq']
    field_simp

/-- T, with the fracpair inverse in place of its own, maps onto `ℚₐ` respecting every operation. -/
theorem toQa_hom_finv :
    Function.Surjective toQa ∧ (∀ x y, toQa (x + y) = Qa.add (toQa x) (toQa y)) ∧
      (∀ x y, toQa (x * y) = Qa.mul (toQa x) (toQa y)) ∧ (∀ x, toQa (-x) = Qa.neg (toQa x)) ∧
      (∀ x, toQa (finv x) = Qa.inv (toQa x)) :=
  ⟨toQa_surjective, toQa_plus, toQa_times, toQa_neg, toQa_finv⟩

/-! ## The equivalence -/

/-- One step of the fracpair equivalence: `x·z / y·(z·z) = x / y·z`. -/
inductive FracStep : T → T → Prop
  | mk (x y z : ℤ) : FracStep ⟨x * z, y * (z * z)⟩ ⟨x, y * z⟩

/-- The fracpair equivalence: the equivalence relation the steps generate. -/
def FracRel : T → T → Prop := Relation.EqvGen FracStep

theorem fracRel_of_step {a b : T} (h : FracStep a b) : FracRel a b := Relation.EqvGen.rel _ _ h

/-- `0/0 = 1/0`: the quarter turn and `0ω` are one fracpair. -/
theorem fracRel_omega_zeroOmega : FracRel «0ω» «ω» := fracRel_of_step (by
  have := FracStep.mk 1 1 0
  simpa [«0ω», «ω»] using this)

/-- `−1 = _1`: the sign moves between the slots. -/
theorem fracRel_negOne : FracRel «-1» «_1» := fracRel_of_step (by
  have := FracStep.mk 1 1 (-1)
  simpa [«-1», «_1»] using this)

/-- `2/4 = 1/2`. -/
theorem fracRel_half : FracRel ⟨2, 4⟩ ⟨1, 2⟩ := fracRel_of_step (by
  have := FracStep.mk 1 1 2
  simpa using this)

/-- `ℚₐ` is an image of the fracpairs: related pairs go to the same place. -/
theorem toQa_of_fracRel {a b : T} (h : FracRel a b) : toQa a = toQa b := by
  induction h with
  | rel a b s =>
    cases s with
    | mk x y z =>
      by_cases hy : y = 0 <;> by_cases hz : z = 0
      · simp [toQa, hy]
      · simp [toQa, hy]
      · simp [toQa, hz]
      · have hy' : (y : ℚ) ≠ 0 := by exact_mod_cast hy
        have hz' : (z : ℚ) ≠ 0 := by exact_mod_cast hz
        simp [toQa, hy, hz]
        field_simp
  | refl => rfl
  | symm _ _ _ ih => exact ih.symm
  | trans _ _ _ _ _ ih₁ ih₂ => exact ih₁.trans ih₂

/-! ## It is a congruence

So the equivalence the steps generate is already closed under the operations, and the fracpairs are its
classes: nothing further is identified by requiring the operations to be well defined. -/

theorem fracStep_plus {a b : T} (h : FracStep a b) (c : T) : FracStep (a + c) (b + c) := by
  cases h with
  | mk x y z =>
    have := FracStep.mk (x * c.q + c.p * (y * z)) (y * c.q) z
    convert this using 2 <;> simp <;> ring

theorem fracStep_times {a b : T} (h : FracStep a b) (c : T) : FracStep (a * c) (b * c) := by
  cases h with
  | mk x y z =>
    have := FracStep.mk (x * c.p) (y * c.q) z
    convert this using 2 <;> simp <;> ring

theorem fracStep_neg {a b : T} (h : FracStep a b) : FracStep (-a) (-b) := by
  cases h with
  | mk x y z =>
    have := FracStep.mk (-x) y z
    convert this using 2 <;> simp

/-- The inverse takes one step to two, through `T(y²z³, xyz²)`. -/
theorem fracRel_finv_of_step {a b : T} (h : FracStep a b) : FracRel (finv a) (finv b) := by
  cases h with
  | mk x y z =>
    have e₁ : finv ⟨x * z, y * (z * z)⟩ = ⟨y * y * (z * z * z) * z, x * y * z * (z * z)⟩ := by
      simp only [finv]; congr 1 <;> ring
    have e₂ : (⟨y * y * (z * z * z), x * y * z * z⟩ : T) = ⟨y * y * (z * z) * z, x * y * (z * z)⟩ := by
      congr 1 <;> ring
    have e₃ : finv ⟨x, y * z⟩ = ⟨y * y * (z * z), x * y * z⟩ := by
      simp only [finv]; congr 1 <;> ring
    rw [e₁, e₃]
    refine Relation.EqvGen.trans _ _ _ (fracRel_of_step (FracStep.mk _ (x * y * z) z)) ?_
    rw [e₂]
    exact fracRel_of_step (FracStep.mk (y * y * (z * z)) (x * y) z)

/-- Carry a step-respecting map through the generated equivalence. -/
theorem fracRel_map {f : T → T} (hf : ∀ {a b}, FracStep a b → FracRel (f a) (f b)) {a b : T}
    (h : FracRel a b) : FracRel (f a) (f b) := by
  induction h with
  | rel a b s => exact hf s
  | refl => exact Relation.EqvGen.refl _
  | symm _ _ _ ih => exact Relation.EqvGen.symm _ _ ih
  | trans _ _ _ _ _ ih₁ ih₂ => exact Relation.EqvGen.trans _ _ _ ih₁ ih₂

theorem fracRel_plus {a b : T} (h : FracRel a b) (c : T) : FracRel (a + c) (b + c) :=
  fracRel_map (fun s => fracRel_of_step (fracStep_plus s c)) h
theorem fracRel_times {a b : T} (h : FracRel a b) (c : T) : FracRel (a * c) (b * c) :=
  fracRel_map (fun s => fracRel_of_step (fracStep_times s c)) h
theorem fracRel_neg {a b : T} (h : FracRel a b) : FracRel (-a) (-b) :=
  fracRel_map (fun s => fracRel_of_step (fracStep_neg s)) h
theorem fracRel_finv {a b : T} (h : FracRel a b) : FracRel (finv a) (finv b) :=
  fracRel_map fracRel_finv_of_step h

/-! ## What the equivalence keeps: the primes of the denominator -/

/-- The primes dividing the denominator. -/
def denomPrimes (x : T) : Finset ℕ := x.q.natAbs.primeFactors

theorem denomPrimes_of_step {a b : T} (h : FracStep a b) : denomPrimes a = denomPrimes b := by
  cases h with
  | mk x y z =>
    simp only [denomPrimes, Int.natAbs_mul]
    by_cases hy : y.natAbs = 0
    · simp [hy]
    by_cases hz : z.natAbs = 0
    · simp [hz]
    rw [Nat.primeFactors_mul hy (mul_ne_zero hz hz), Nat.primeFactors_mul hz hz,
      Nat.primeFactors_mul hy hz, Finset.union_idempotent]

theorem denomPrimes_of_fracRel {a b : T} (h : FracRel a b) : denomPrimes a = denomPrimes b := by
  induction h with
  | rel a b s => exact denomPrimes_of_step s
  | refl => rfl
  | symm _ _ _ ih => exact ih.symm
  | trans _ _ _ _ _ ih₁ ih₂ => exact ih₁.trans ih₂

/-- `2/2` is not `1/1` as a fracpair, though it is in `ℚₐ`. -/
theorem not_fracRel_two_two : ¬ FracRel ⟨2, 2⟩ «1» := fun h => by
  have := denomPrimes_of_fracRel h
  simp [denomPrimes, «1»] at this

/-- `0·(1/2) = T(0,2)` is not `0` as a fracpair, though it is in `ℚₐ`. -/
theorem not_fracRel_zero_two : ¬ FracRel ⟨0, 2⟩ 0 := fun h => by
  have := denomPrimes_of_fracRel h
  simp [denomPrimes] at this

example : toQa ⟨2, 2⟩ = toQa «1» ∧ toQa ⟨0, 2⟩ = toQa 0 := by
  simp [toQa, «1»]

end T
